### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by jmohta** [dragen1860/DARTS-PyTorch#2]
When I run the current version of the code on my machine I am getting an run time error saying that one of the differentiated Tensors is unused. 
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.
It is showing the error on this line: dtheta = concat(autograd.grad(loss, self.model.parameters())).data (this is from arch.py)
Can you please help me to resolve the issue? Thank you in advance.

**Comment by dragen1860** [comment]
Hi, @JayMohta1997 , could you tell me your pytorch version and python version.
According to my test, it has no problem on my Pytorch 1.0, pytorch 3.6 platfrom.

**Comment by jmohta** [comment]
Hi, Pytorch Version that I am using is 0.4.0
Python Version is 3.5.6
Let me know if you need any more information. Thank you.

**Comment by dragen1860** [comment]
Hi, Maybe you need to update to pytorch 1.0.

**Comment by jmohta** [comment]
Hi, Still getting the same problem. I am running the code on CPU so I have deleted all the cuda instances from your code. I don't think that would be creating the above error. Let me know your views. Thanks.

**Comment by dragen1860** [comment]
,,.
I never tested on CPU.
Sure it should not be caused by cpu mode. But as a way to reduce possibility of causes, you should run as the typical way and then find the potential bug step by step.

**Comment by jmohta** [comment]
I tried to run the code on GPU it's running without any errors. I guess pytorch CPU version was creating some problem. Thank you for your time and help.
